In [2]:
print('hi')

hi


In [3]:
#импорт библиотеки
import numpy as np


In [5]:
#массив из 10 нулей
array=np.zeros(10)
print("10 null")
print(array) 

10 edinic
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#массив из 10 единиц
array=np.ones(10)
print("10 edinic")
print(array)

10 edinic
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#массив из 10 пятерок
array=np.ones(10)*5
print("10 pyaterok:")
print(array)

10 pyaterok:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
#массив из целых чисел от 10 до 50
array=np.arange(10,51)
print('ot10 do 50')
print(array)

ot10 do 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
#массив из четных чисел от 10 до 50
for a in range(10, 51, 2):
   print (a)


10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [14]:
from numpy.matrixlib.defmatrix import matrix
#матрицу 3х3 с числами от 0 до 8
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#единичную матрицу 3x3
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#NumPy для генерации случайного числа от 0 до 1
rand = np.random.rand(1)
print("ot 0 do 1")
print(rand)

ot 0 do 1
[0.41078357]


In [28]:
#NumPy для генерации массива из 25 случайных чисел
rand=np.random.rand(25)
print("25 random numbers:")
print(rand)


25 random numbers:
[0.68341329 0.41775925 0.26634057 0.03612299 0.61764275 0.62683463
 0.07793315 0.58047613 0.68217764 0.32271658 0.66953749 0.27746672
 0.80943861 0.33907694 0.39579363 0.44169517 0.9645396  0.76519299
 0.45984495 0.22829894 0.4225041  0.41044597 0.81649668 0.44593487
 0.97836038]


In [29]:
#Создайте следующую матрицу используя функции библиотеки NumPy
mat=np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [30]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
#Необходимо написать код который вернет следующую матрицуиз стартовой
print('1=', mat[0:,0:])

1= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
dv=mat[mat==20]
print(dv)

[20]


In [33]:
print('n=', mat[0:3,1].reshape(3,1))

n= [[ 2]
 [ 7]
 [12]]


In [38]:
print('1=',mat[4:])

1= [[21 22 23 24 25]]


In [41]:
print('p=', mat[3:])

p= [[16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
print(mat.sum())

325


In [43]:
print(mat.std())

7.211102550927978


In [44]:
print(mat.sum(axis=0))

[55 60 65 70 75]
